# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'cookbook' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for cookbook
  pod 'Firebase/Core'
end

target 'cookbookTests' do
  inherit! :search_paths
  # Pods for testing
  pod 'Firebase/Core'
  pod 'Firebase/Database'
end


